server {
	listen 443 ssl;
	server_name mmaarafi.42.fr;

	ssl_certificate     /etc/nginx/ssl/mmaarafi.42.crt;
	ssl_certificate_key /etc/nginx/ssl/mmaarafi.42.key;

	ssl_protocols TLSv1.2 TLSv1.3;

	# root define which folder to search in
	root /var/www/wordpress;
	# in case the uri only contain "/" then this define the order of which index to serve first
	index index.php index.html index.htm;
	# there are 3 cases here we found the exact uri meaning a file match we found the uri but its a folder
	# the last case we didnt find anything in that case nginx treat the uri as if it end .php so wordpress handle everything
	# also here we included $args so if the urin contain other argument they get sent to wordpress
	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}